# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('storage_filename', models.CharField(max_length=256)),
                ('displayed_filename', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
