# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 14:21
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0001_squashed_0055_file_mentioned_persons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization'),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='search_string',
            field=models.TextField(),
        ),
    ]
