# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 11:29
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0004_auto_20180112_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='sort_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='sort_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
