# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20170910_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Paper'),
        ),
    ]
