# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_agendaitem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaitem',
            options={'ordering': ['meeting', 'position']},
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='is_change_request_of',
            new_name='change_request_of',
        ),
    ]
