# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20170910_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='submitter_committee',
            new_name='submitter_committees',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='submitter_department',
            new_name='submitter_departments',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='submitter_parliamentary_group',
            new_name='submitter_parliamentary_groups',
        ),
    ]
