# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20170910_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legislativeterm',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='legislativeterm',
            old_name='start_date',
            new_name='start',
        ),
        migrations.AddField(
            model_name='committee',
            name='end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='committee',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
