# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0008_auto_20180216_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='short_name',
        ),
    ]
