# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20170911_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='locations',
            new_name='location',
        ),
    ]
