# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0010_auto_20180216_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
