# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.sites.models import Site
from django.db import migrations


def update_site(apps, schema_editor):
    Site.objects.create(name=settings.PRODUCT_NAME, domain=settings.REAL_HOST).save()


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0011_userprofile'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(update_site),
    ]
