# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0011_auto_20180216_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='locality',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='postalCode',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='room',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='locality',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='postalCode',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='room',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
