# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.contrib.sites.models import Site
from django.db import migrations, models
import django.db.models.deletion


def update_site(apps, schema_editor):
    current_site = Site.objects.get_current()
    current_site.domain = "opensourceris.local"
    current_site.name = "Open Source Ratsinformationssystem"
    current_site.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0011_userprofile'),
    ]

    operations = [
        migrations.RunPython(update_site),
    ]
