# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_meetingseries_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(default='FIXME', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='FIXME', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='displayed_filename',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='storage_filename',
            field=models.CharField(max_length=200),
        ),
    ]
