# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20170924_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
