# Generated by Django 2.1.3 on 2018-12-02 21:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0015_auto_20181116_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='storage_filename',
        ),
        migrations.RemoveField(
            model_name='historicalfile',
            name='storage_filename',
        ),
    ]
