# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_auto_20170924_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parliamentarygroup',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
