# Generated by Django 2.1.4 on 2018-12-21 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0016_auto_20181202_2205'),
        ('mainapp', '0016_auto_20181221_1432'),
    ]

    operations = [
    ]
