# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20170924_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
