# Generated by Django 2.1.4 on 2018-12-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0018_auto_20181227_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsearchstreet',
            name='osm_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchstreet',
            name='osm_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
