# Generated by Django 2.1.4 on 2019-01-06 12:37

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0019_auto_20181227_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalOrganizationMembership',
            new_name='HistoricalMembership',
        ),
        migrations.RenameModel(
            old_name='OrganizationMembership',
            new_name='Membership',
        ),
        migrations.AlterModelOptions(
            name='historicalmembership',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'),
                     'verbose_name': 'historical membership'},
        ),
        migrations.RemoveIndex(
            model_name='paper',
            name='mainapp_pap_sort_da_a4a03b_idx',
        ),
        migrations.RenameField(
            model_name='agendaitem',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='displayed_filename',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='historicalagendaitem',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='historicalfile',
            old_name='displayed_filename',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='historicallocation',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='historicallocation',
            old_name='streetAddress',
            new_name='street_address',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='postalCode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='streetAddress',
            new_name='street_address',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicalconsultation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='historicalpaper',
            name='description',
        ),
        migrations.RemoveField(
            model_name='location',
            name='bodies',
        ),
        migrations.RemoveField(
            model_name='location',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='description',
        ),
        migrations.AddField(
            model_name='body',
            name='ags',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='historicalbody',
            name='ags',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='filesize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sort_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='filesize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='sort_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalpaper',
            name='sort_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paper',
            name='sort_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
