# Generated by Django 2.1.4 on 2019-01-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0020_auto_20190106_1337'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['-sort_date'], name='mainapp_pap_sort_da_45833e_idx'),
        ),
    ]
