# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_auto_20171004_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmembership',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departmentmembership',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
