# Generated by Django 2.1.8 on 2019-04-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0021_auto_20190106_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='family_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='given_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='given_name',
            field=models.CharField(max_length=100),
        ),
    ]
