# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_auto_20171004_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemembership',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
