# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_auto_20171004_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='legal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
