# Generated by Django 2.1.11 on 2019-09-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0024_merge_20190405_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmeeting',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
