# Generated by Django 2.1.11 on 2019-09-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20190917_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='search_str',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='search_str',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
