# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_paper_main_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
