# Generated by Django 2.2.9 on 2020-01-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0026_auto_20190930_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallegislativeterm',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legislativeterm',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
