# Generated by Django 2.2.13 on 2020-06-09 14:40

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0027_auto_20200107_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaper',
            name='display_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='display_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='sort_date',
            field=models.DateTimeField(default=datetime.datetime(1994, 12, 31, 23, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='sort_date',
            field=models.DateTimeField(default=datetime.datetime(1994, 12, 31, 23, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='historicalpaper',
            name='sort_date',
            field=models.DateTimeField(default=datetime.datetime(1994, 12, 31, 23, 0, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='sort_date',
            field=models.DateTimeField(default=datetime.datetime(1994, 12, 31, 23, 0, tzinfo=utc)),
        ),
    ]
