# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_auto_20171007_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeemembership',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parliamentarygroupmembership',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
