# Generated by Django 3.1.5 on 2021-01-25 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0029_auto_20201206_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='manually_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='manually_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
