# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_auto_20171027_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='title',
            field=models.CharField(max_length=2000),
        ),
    ]
