# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20171029_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
