# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_paper_paper_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='paper',
            name='paper_type',
        ),
    ]
