# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_paper_paper_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
