# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20171030_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
