# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_consultation_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Meeting'),
        ),
    ]
