# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_auto_20171117_1536'),
        ('mainapp', '0041_remove_userprofile_email_is_verified'),
    ]

    operations = [
    ]
