# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_merge_20171117_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oparl_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=6, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Body')),
                ('legislative_terms', models.ManyToManyField(blank=True, to='mainapp.LegislativeTerm')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oparl_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('role', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='committee',
            name='body',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='legislative_terms',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='committeemembership',
            name='committee',
        ),
        migrations.RemoveField(
            model_name='committeemembership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='department',
            name='body',
        ),
        migrations.RemoveField(
            model_name='department',
            name='location',
        ),
        migrations.RemoveField(
            model_name='departmentmembership',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentmembership',
            name='person',
        ),
        migrations.RemoveField(
            model_name='parliamentarygroup',
            name='body',
        ),
        migrations.RemoveField(
            model_name='parliamentarygroup',
            name='legislative_terms',
        ),
        migrations.RemoveField(
            model_name='parliamentarygroup',
            name='location',
        ),
        migrations.RemoveField(
            model_name='parliamentarygroupmembership',
            name='parliamentary_group',
        ),
        migrations.RemoveField(
            model_name='parliamentarygroupmembership',
            name='person',
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='submitter_persons',
            new_name='persons',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='committees',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='submitter_committees',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='submitter_departments',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='submitter_parliamentary_groups',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
        migrations.DeleteModel(
            name='CommitteeMembership',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DepartmentMembership',
        ),
        migrations.DeleteModel(
            name='ParliamentaryGroup',
        ),
        migrations.DeleteModel(
            name='ParliamentaryGroupMembership',
        ),
        migrations.AddField(
            model_name='meeting',
            name='organization',
            field=models.ManyToManyField(blank=True, to='mainapp.Organization'),
        ),
        migrations.AddField(
            model_name='paper',
            name='organization',
            field=models.ManyToManyField(blank=True, to='mainapp.Organization'),
        ),
    ]
