# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_auto_20171117_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='organization',
            new_name='organizations',
        ),
    ]
