# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0047_auto_20171117_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization'),
        ),
    ]
