# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0050_auto_20171124_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='organizations',
            field=models.ManyToManyField(blank=True, to='mainapp.Organization'),
        ),
    ]
