# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0051_consultation_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
