# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0052_file_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='key',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
