# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0053_auto_20171208_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='body',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legislativeterm',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='legislativeterm',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.TextField(),
        ),
    ]
