# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0054_auto_20171209_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='mentioned_persons',
            field=models.ManyToManyField(blank=True, to='mainapp.Person'),
        ),
    ]
