# Generated by Django 2.1.8 on 2019-05-07 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'Eine Seite mit einem Titel und Inhalt'},
        ),
        migrations.AlterModelOptions(
            name='glossarypage',
            options={'verbose_name': 'Ein Glossar'},
        ),
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'Die Startseite des CMS-Teils'},
        ),
    ]
