# Generated by Django 2.2.12 on 2020-05-07 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0002_auto_20190507_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'A page with a title and some content'},
        ),
        migrations.AlterModelOptions(
            name='glossarypage',
            options={'verbose_name': 'A glossary'},
        ),
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'The landing page for the cms section'},
        ),
    ]
