# Generated by Django 2.2.13 on 2020-06-09 14:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cms', '0003_auto_20200507_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpage',
            options={'verbose_name': 'Eine Seite mit einem Titel und Inhalt'},
        ),
        migrations.AlterModelOptions(
            name='glossarypage',
            options={'verbose_name': 'Ein Glossar'},
        ),
        migrations.AlterModelOptions(
            name='indexpage',
            options={'verbose_name': 'Die Startseite des CMS-Teils'},
        ),
    ]
