# Generated by Django 2.1.4 on 2019-01-06 12:37

import django.db.models.deletion
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('mainapp', '0020_auto_20190106_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('data', jsonfield.fields.JSONField()),
                ('oparl_type', models.CharField(max_length=100)),
                ('to_import', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FileQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
                ('if_modified_since', models.DateTimeField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.File')),
            ],
        ),
    ]
